### ISSUE TITLE
useful_package: signal-desktop

### ISSUE THREAD

**Issue by maehsi** [ghostbsd/ghostbsd-ci#9]
I would like signal-desktop to always work on GhostBSD, if possible.
Thank you.

**Comment by maehsi** [comment]
OK, maybe this isn't such a great idea after all? https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270565

**Comment by ericbsd** [comment]
I will add it, and if it becomes a problem, I can remove it later.

By the way, signal-desktop will be available to install in 25 min.
